### ISSUE TITLE
mocks + spec2 + spec2-mocks trouble?

### ISSUE THREAD

**Issue by vjdhama** [waterlink/spec2-mocks.cr#5]
I just updated the development dependencies for my project, and added `spec2-mocks` as suggested [here](https://github.com/waterlink/mocks.cr/#usage-with-spec2-library). I am using mock like this now.

``` crystal
Mock.create_mock File do
   mock self.exists?(path)
end
```

But when i run `crystal spec` it throws this error.

```
$ crystal spec
Error in ./libs/spec2-mocks/spec2-mocks.cr:64: undefined constant ::Mocks::Macro::GlobalDSL

  include ::Mocks::Macro::GlobalDSL
          ^~~~~~~~~~~~~~~~~~~~~~~~~
```

Am I missing something?

**Comment by vjdhama** [comment]
Just leaving versions of dependencies here.

```
mocks (0.9.1)
spec2-mocks (0.3.0)
spec2 (0.8.0)
```

**Comment by vjdhama** [comment]
By the way I'm using latest crystal(v0.15).

**Comment by waterlink** [comment]
`spec2-mocks` needs to be upgraded to a newer `mocks` version.

**Comment by waterlink** [comment]
I will do that and release a new version

**Comment by waterlink** [comment]
Seems to be a crystal version upgrade. I don't have that error..

**Comment by waterlink** [comment]
Works for me with these versions:
- `spec2-mocks: 0.3.1`
- `mocks: 0.9.1`
- `spec2: 0.8.0`

Could you try to upgrade to `0.3.1` of `spec2-mocks` ?

If it still doesn't work, could you please provide an example code to reproduce the failure?

**Comment by vjdhama** [comment]
Lemme try upgrading to `0.3.1` of `spec2-mocks` .

**Comment by vjdhama** [comment]
Works like a charm. Thanks. :trophy:

**Comment by waterlink** [comment]
No problem :)
